using SpreadCheetah.Worksheets;

namespace SpreadCheetah.SourceGeneration;

/// <summary>
/// <para>
/// Instructs the SpreadCheetah source generator about the width to use for a column.
/// The number represents how many characters can be displayed in the standard font.
/// It must be between 0 and 255. When not set Excel will default to 8.43.
/// </para>
/// <para>
/// A worksheet will use column widths from this attribute by passing the
/// <see cref="WorksheetRowTypeInfo{T}"/> type generated by the source generator to
/// <see cref="Spreadsheet.StartWorksheetAsync{T}(string, WorksheetRowTypeInfo{T}, CancellationToken)" />.
/// </para>
/// <para>
/// Alternatively, use <see cref="WorksheetRowTypeInfo{T}.CreateWorksheetOptions"/> to create an
/// instance of <see cref="WorksheetOptions"/> with column widths set. More options can then
/// be set on the <see cref="WorksheetOptions"/> instance before passing it to
/// <see cref="Spreadsheet.StartWorksheetAsync(string, WorksheetOptions?, CancellationToken)" />.
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public sealed class ColumnWidthAttribute(double width) : Attribute
{
    /// <summary>
    /// Returns the constructor's <c>width</c> argument value.
    /// </summary>
    public double? Width { get; } = width;
}
