using SpreadCheetah.Worksheets;

namespace SpreadCheetah.SourceGeneration;

/// <summary>
/// <para>
/// Instructs the SpreadCheetah source generator to set a default width for all columns in the worksheet.
/// The number represents how many characters can be displayed in the standard font.
/// It must be between 0 and 255. When not set Excel will default to approximately 8.89.
/// </para>
/// <para>
/// This attribute must be placed at the class level.
/// Individual columns can override this default width by using <see cref="ColumnWidthAttribute"/> on properties.
/// </para>
/// <para>
/// A worksheet will use this default column width by passing the
/// <see cref="WorksheetRowTypeInfo{T}"/> type generated by the source generator to
/// <see cref="Spreadsheet.StartWorksheetAsync{T}(string, WorksheetRowTypeInfo{T}, CancellationToken)" />.
/// </para>
/// <para>
/// Alternatively, use <see cref="WorksheetRowTypeInfo{T}.CreateWorksheetOptions"/> to create an
/// instance of <see cref="WorksheetOptions"/> with column widths set. More options can then
/// be set on the <see cref="WorksheetOptions"/> instance before passing it to
/// <see cref="Spreadsheet.StartWorksheetAsync(string, WorksheetOptions?, CancellationToken)" />.
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public sealed class DefaultColumnWidthAttribute(double width) : Attribute
{
    /// <summary>
    /// Returns the constructor's <c>width</c> argument value.
    /// </summary>
    public double? Width { get; } = width;
}
