using SpreadCheetah.SourceGeneration.Internal;
using SpreadCheetah.Styling;
using SpreadCheetah.Worksheets;

namespace SpreadCheetah.SourceGeneration;

/// <summary>
/// Used by code generated by the source generator and is not intended to be used directly.
/// Provides helpers used by code generated by the source generator.
/// </summary>
public static class WorksheetRowMetadataServices
{
    /// <summary>
    /// Used by code generated by the source generator and is not intended to be used directly.
    /// Creates metadata for a row type.
    /// </summary>
    public static WorksheetRowTypeInfo<T> CreateObjectInfo<T>(
        Func<Spreadsheet, StyleId?, CancellationToken, ValueTask> headerHandler,
        Func<Spreadsheet, T, CancellationToken, ValueTask> rowHandler,
        Func<Spreadsheet, IEnumerable<T>, CancellationToken, ValueTask> rowRangeHandler,
        Func<WorksheetOptions>? worksheetOptionsFactory = null,
        Func<Spreadsheet, WorksheetRowDependencyInfo>? createWorksheetRowDependencyInfo = null)
        => new WorksheetRowTypeInfoInternal<T>(headerHandler, rowHandler, rowRangeHandler, worksheetOptionsFactory, createWorksheetRowDependencyInfo);
}
