using SpreadCheetah.SourceGeneration.Internal;

namespace SpreadCheetah.SourceGeneration;

/// <summary>
/// Provides helpers used by code generated by the SpreadCheetah source generator.
/// </summary>
public static class WorksheetRowMetadataServices
{
    /// <summary>
    /// Creates metadata for a row type.
    /// </summary>
    public static WorksheetRowTypeInfo<T> CreateObjectInfo<T>(
        Func<Spreadsheet, T, CancellationToken, ValueTask> rowHandler,
        Func<Spreadsheet, IEnumerable<T>, CancellationToken, ValueTask> rowRangeHandler)
        => new WorksheetRowTypeInfoInternal<T>(rowHandler, rowRangeHandler);
}
