//HintName: MyNamespace.MyContext.g.cs
// <auto-generated />
#nullable enable
using SpreadCheetah;
using SpreadCheetah.SourceGeneration;
using SpreadCheetah.Styling;
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MyNamespace
{
    public partial class MyContext
    {
        private static MyContext? _default;
        public static MyContext Default => _default ??= new MyContext();

        public MyContext()
        {
        }

        private WorksheetRowTypeInfo<MyNamespace.ClassWithAllSupportedTypes>? _ClassWithAllSupportedTypes;
        public WorksheetRowTypeInfo<MyNamespace.ClassWithAllSupportedTypes> ClassWithAllSupportedTypes => _ClassWithAllSupportedTypes
            ??= WorksheetRowMetadataServices.CreateObjectInfo<MyNamespace.ClassWithAllSupportedTypes>(
                AddHeaderRow0Async, AddAsRowAsync, AddRangeAsRowsAsync, null);

        private static async ValueTask AddHeaderRow0Async(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.Styling.StyleId? styleId, CancellationToken token)
        {
            var headerNames = ArrayPool<string?>.Shared.Rent(16);
            try
            {
                headerNames[0] = "StringValue";
                headerNames[1] = "NullableStringValue";
                headerNames[2] = "IntValue";
                headerNames[3] = "NullableIntValue";
                headerNames[4] = "LongValue";
                headerNames[5] = "NullableLongValue";
                headerNames[6] = "FloatValue";
                headerNames[7] = "NullableFloatValue";
                headerNames[8] = "DoubleValue";
                headerNames[9] = "NullableDoubleValue";
                headerNames[10] = "DecimalValue";
                headerNames[11] = "NullableDecimalValue";
                headerNames[12] = "DateTimeValue";
                headerNames[13] = "NullableDateTimeValue";
                headerNames[14] = "BoolValue";
                headerNames[15] = "NullableBoolValue";
                await spreadsheet.AddHeaderRowAsync(headerNames.AsMemory(0, 16), styleId, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<string?>.Shared.Return(headerNames, true);
            }
        }

        private static ValueTask AddAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet, MyNamespace.ClassWithAllSupportedTypes? obj, CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);
            return AddAsRowInternalAsync(spreadsheet, obj, token);
        }

        private static ValueTask AddRangeAsRowsAsync(SpreadCheetah.Spreadsheet spreadsheet,
            IEnumerable<MyNamespace.ClassWithAllSupportedTypes?> objs,
            CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (objs is null)
                throw new ArgumentNullException(nameof(objs));
            return AddRangeAsRowsInternalAsync(spreadsheet, objs, token);
        }

        private static async ValueTask AddAsRowInternalAsync(SpreadCheetah.Spreadsheet spreadsheet,
            MyNamespace.ClassWithAllSupportedTypes obj,
            CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(16);
            try
            {
                var styleIds = Array.Empty<StyleId>();
                await AddCellsAsRowAsync(spreadsheet, obj, cells, styleIds, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static async ValueTask AddRangeAsRowsInternalAsync(SpreadCheetah.Spreadsheet spreadsheet,
            IEnumerable<MyNamespace.ClassWithAllSupportedTypes?> objs,
            CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(16);
            try
            {
                var styleIds = Array.Empty<StyleId>();
                foreach (var obj in objs)
                {
                    await AddCellsAsRowAsync(spreadsheet, obj, cells, styleIds, token).ConfigureAwait(false);
                }
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static ValueTask AddCellsAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet,
            MyNamespace.ClassWithAllSupportedTypes? obj,
            DataCell[] cells, IReadOnlyList<StyleId> styleIds, CancellationToken token)
        {
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);

            cells[0] = new DataCell(obj.StringValue);
            cells[1] = new DataCell(obj.NullableStringValue);
            cells[2] = new DataCell(obj.IntValue);
            cells[3] = new DataCell(obj.NullableIntValue);
            cells[4] = new DataCell(obj.LongValue);
            cells[5] = new DataCell(obj.NullableLongValue);
            cells[6] = new DataCell(obj.FloatValue);
            cells[7] = new DataCell(obj.NullableFloatValue);
            cells[8] = new DataCell(obj.DoubleValue);
            cells[9] = new DataCell(obj.NullableDoubleValue);
            cells[10] = new DataCell(obj.DecimalValue);
            cells[11] = new DataCell(obj.NullableDecimalValue);
            cells[12] = new DataCell(obj.DateTimeValue);
            cells[13] = new DataCell(obj.NullableDateTimeValue);
            cells[14] = new DataCell(obj.BoolValue);
            cells[15] = new DataCell(obj.NullableBoolValue);
            return spreadsheet.AddRowAsync(cells.AsMemory(0, 16), token);
        }

        private static DataCell ConstructTruncatedDataCell(string? value, int truncateLength)
        {
            return value is null || value.Length <= truncateLength
                ? new DataCell(value)
                : new DataCell(value.AsMemory(0, truncateLength));
        }
    }
}
