//HintName: MyNamespace.MyContext.g.cs
// <auto-generated />
#nullable enable
using SpreadCheetah;
using SpreadCheetah.SourceGeneration;
using SpreadCheetah.Styling;
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MyNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SpreadCheetah.SourceGenerator", "1.0.0")]
    public partial class MyContext
    {
        private static MyContext? _default;

        /// <summary>The default context instance.</summary>
        public static MyContext Default => _default ??= new MyContext();

        /// <inheritdoc/>
        public MyContext()
        {
        }

        private WorksheetRowTypeInfo<MyNamespace.MyClass>? _MyClass;

        /// <summary>
        /// Defines the source generated worksheet row metadata for a given type.
        /// </summary>
        public WorksheetRowTypeInfo<MyNamespace.MyClass> MyClass => _MyClass
            ??= EmptyWorksheetRowContext.CreateTypeInfo<MyNamespace.MyClass>();
    }
}
