//HintName: MyNamespace.MyGenRowContext.g.cs
// <auto-generated />
#nullable enable
using SpreadCheetah;
using SpreadCheetah.SourceGeneration;
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MyNamespace
{
    public partial class MyGenRowContext
    {
        private static MyGenRowContext? _default;
        public static MyGenRowContext Default => _default ??= new MyGenRowContext();

        public MyGenRowContext()
        {
        }

        private WorksheetRowTypeInfo<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders>? _ClassWithInvalidPropertyReferenceColumnHeaders;
        public WorksheetRowTypeInfo<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders> ClassWithInvalidPropertyReferenceColumnHeaders => _ClassWithInvalidPropertyReferenceColumnHeaders
            ??= WorksheetRowMetadataServices.CreateObjectInfo<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders>(AddHeaderRow0Async, AddAsRowAsync, AddRangeAsRowsAsync);

        private static async ValueTask AddHeaderRow0Async(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.Styling.StyleId? styleId, CancellationToken token)
        {
            var cells = ArrayPool<StyledCell>.Shared.Rent(7);
            try
            {
                cells[0] = new StyledCell("PropertyA", styleId);
                cells[1] = new StyledCell("PropertyB", styleId);
                cells[2] = new StyledCell("PropertyC", styleId);
                cells[3] = new StyledCell("PropertyD", styleId);
                cells[4] = new StyledCell("PropertyE", styleId);
                cells[5] = new StyledCell("PropertyF", styleId);
                cells[6] = new StyledCell("PropertyG", styleId);
                await spreadsheet.AddRowAsync(cells.AsMemory(0, 7), token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<StyledCell>.Shared.Return(cells, true);
            }
        }

        private static ValueTask AddAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet, MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders? obj, CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);
            return AddAsRowInternalAsync(spreadsheet, obj, token);
        }

        private static ValueTask AddRangeAsRowsAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders?> objs, CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (objs is null)
                throw new ArgumentNullException(nameof(objs));
            return AddRangeAsRowsInternalAsync(spreadsheet, objs, token);
        }

        private static async ValueTask AddAsRowInternalAsync(SpreadCheetah.Spreadsheet spreadsheet, MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders obj, CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(7);
            try
            {
                await AddCellsAsRowAsync(spreadsheet, obj, cells, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static async ValueTask AddRangeAsRowsInternalAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders?> objs, CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(7);
            try
            {
                await AddEnumerableAsRowsAsync(spreadsheet, objs, cells, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static async ValueTask AddEnumerableAsRowsAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders?> objs, DataCell[] cells, CancellationToken token)
        {
            foreach (var obj in objs)
            {
                await AddCellsAsRowAsync(spreadsheet, obj, cells, token).ConfigureAwait(false);
            }
        }

        private static ValueTask AddCellsAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet, MyNamespace.ClassWithInvalidPropertyReferenceColumnHeaders? obj, DataCell[] cells, CancellationToken token)
        {
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);

            cells[0] = new DataCell(obj.PropertyA);
            cells[1] = new DataCell(obj.PropertyB);
            cells[2] = new DataCell(obj.PropertyC);
            cells[3] = new DataCell(obj.PropertyD);
            cells[4] = new DataCell(obj.PropertyE);
            cells[5] = new DataCell(obj.PropertyF);
            cells[6] = new DataCell(obj.PropertyG);
            return spreadsheet.AddRowAsync(cells.AsMemory(0, 7), token);
        }
    }
}
