//HintName: MyNamespace.MyGenRowContext.g.cs
// <auto-generated />
#nullable enable
using SpreadCheetah;
using SpreadCheetah.SourceGeneration;
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace MyNamespace
{
    public partial class MyGenRowContext
    {
        private static MyGenRowContext? _default;
        public static MyGenRowContext Default => _default ??= new MyGenRowContext();

        public MyGenRowContext()
        {
        }

        private WorksheetRowTypeInfo<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance>? _RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance;
        public WorksheetRowTypeInfo<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance> RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance => _RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance
            ??= WorksheetRowMetadataServices.CreateObjectInfo<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance>(AddHeaderRow0Async, AddAsRowAsync, AddRangeAsRowsAsync);

        private static async ValueTask AddHeaderRow0Async(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.Styling.StyleId? styleId, CancellationToken token)
        {
            var cells = ArrayPool<StyledCell>.Shared.Rent(3);
            try
            {
                cells[0] = new StyledCell("Name", styleId);
                cells[1] = new StyledCell("Age", styleId);
                cells[2] = new StyledCell("ClassProperty", styleId);
                await spreadsheet.AddRowAsync(cells.AsMemory(0, 3), token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<StyledCell>.Shared.Return(cells, true);
            }
        }

        private static ValueTask AddAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance? obj, CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);
            return AddAsRowInternalAsync(spreadsheet, obj, token);
        }

        private static ValueTask AddRangeAsRowsAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance?> objs, CancellationToken token)
        {
            if (spreadsheet is null)
                throw new ArgumentNullException(nameof(spreadsheet));
            if (objs is null)
                throw new ArgumentNullException(nameof(objs));
            return AddRangeAsRowsInternalAsync(spreadsheet, objs, token);
        }

        private static async ValueTask AddAsRowInternalAsync(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance obj, CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(3);
            try
            {
                await AddCellsAsRowAsync(spreadsheet, obj, cells, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static async ValueTask AddRangeAsRowsInternalAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance?> objs, CancellationToken token)
        {
            var cells = ArrayPool<DataCell>.Shared.Rent(3);
            try
            {
                await AddEnumerableAsRowsAsync(spreadsheet, objs, cells, token).ConfigureAwait(false);
            }
            finally
            {
                ArrayPool<DataCell>.Shared.Return(cells, true);
            }
        }

        private static async ValueTask AddEnumerableAsRowsAsync(SpreadCheetah.Spreadsheet spreadsheet, IEnumerable<SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance?> objs, DataCell[] cells, CancellationToken token)
        {
            foreach (var obj in objs)
            {
                await AddCellsAsRowAsync(spreadsheet, obj, cells, token).ConfigureAwait(false);
            }
        }

        private static ValueTask AddCellsAsRowAsync(SpreadCheetah.Spreadsheet spreadsheet, SpreadCheetah.SourceGenerator.SnapshotTest.Models.InheritColumns.RecordClass2LevelOfInheritanceInheritedColumnsFirstParentIgnoreInheritance? obj, DataCell[] cells, CancellationToken token)
        {
            if (obj is null)
                return spreadsheet.AddRowAsync(ReadOnlyMemory<DataCell>.Empty, token);

            cells[0] = new DataCell(obj.Name);
            cells[1] = new DataCell(obj.Age);
            cells[2] = new DataCell(obj.ClassProperty);
            return spreadsheet.AddRowAsync(cells.AsMemory(0, 3), token);
        }
    }
}
